[package]
name = "advent_of_code_23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array2d = "0.3.0"
clap = { version = "4.4.11", features = ["derive"] }
num-integer = "0.1.45"
rayon = "1.8.0"
